export function detectIsFemaleByName(name: string): boolean {
  if (!name || typeof name !== "string") return false;

  const normalized = name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();

  const firstName = normalized.split(/\s+/)[0]?.toLowerCase();
  if (!firstName) return false;

  const maleExceptions = new Set([
    "luca",
    "lucas",
    "sasha",
    "euma",
    "mustafa",
    "joshua",
    "akira",
    "borba",
    "garcia",
    "elias",
    "matias",
    "alencar",
    "alessandro",
  ]);

  if (maleExceptions.has(firstName)) return false;

  const femaleNames = new Set([
    "ana",
    "maria",
    "juliana",
    "mariana",
    "fernanda",
    "beatriz",
    "camila",
    "larissa",
    "carla",
    "paula",
    "patricia",
    "jessica",
    "aline",
    "amanda",
    "leticia",
    "bruna",
    "gabriela",
    "vanessa",
    "rafaela",
    "carolina",
    "luana",
    "thais",
    "isabela",
    "sofia",
    "clara",
    "alice",
    "laura",
    "helena",
    "giovanna",
    "livia",
    "manuela",
    "valentina",
    "lorena",
    "nathalia",
    "natalia",
    "mirella",
    "evelyn",
    "ingrid",
    "jaqueline",
    "priscila",
    "renata",
    "tatiane",
    "vitoria",
    "yasmin",
    "marta",
    "cristiane",
    "debora",
    "luciana",
    "sabrina",
    "roberta",
    "daniela",
    "isabel",
    "racquel",
    "raquel",
    "samara",
    "monique",
    "luiza",
    "luisa",
    "michele",
    "michelle",
    "flavia",
    "simone",
    "sandra",
    "sonia",
    "sueli",
    "andressa",
    "andrea",
    "denise",
    "elisabeth",
    "elizabeth",
    "erika",
    "fabiana",
    "fatima",
    "franciele",
    "giselle",
    "gisele",
    "isadora",
    "joana",
    "karina",
    "karen",
    "lais",
    "lara",
    "lourdes",
    "maira",
    "marcela",
    "marcia",
    "margarete",
    "marlene",
    "mayara",
    "milena",
    "monica",
    "nayara",
    "nicole",
    "paloma",
    "pamela",
    "rebeca",
    "regina",
    "rosana",
    "rosangela",
    "rose",
    "silvia",
    "stefany",
    "stephanie",
    "tais",
    "tatiana",
    "tereza",
    "teresa",
    "veronica",
    "viviane",
  ]);

  if (femaleNames.has(firstName)) return true;

  if (firstName.endsWith("a") && firstName.length >= 3) {
    return true;
  }

  return false;
}
